title: Reinventing the Wheel
subtitle: Wheel's Development Blog
baseurl: ''
timezone: Asia/Seoul
plugins:
- jekyll-sitemap
- jekyll-feed
exclude:
- run
- commit
- updateCollection
- createTIL
- README.md
- Gemfile
- Gemfile.lock
- _scripts
- _config
- requirements.txt
assets: /assets
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes
collections_dir: documents
sass:
  sass_dir: _sass
markdown: kramdown
kramdown:
  auto_id_prefix: kramdown_
  auto_ids: true
  smart_quotes:
  - apos
  - apos
  - quot
  - quot
home_recent_doc_num: 10
decoration: ''
collections:
  sysdoc:
    name: sysdoc
    output: true
    permalink: /:name
  SKKU_swe3050:
    category: 기계학습 (Machine Learning)
    name: 기계학습원론
    output: true
    permalink: /:collection/:name
    tags:
    - lecture
    - machine_learning
    - skku
  SNU_m3309.000200:
    category: 기계학습 (Machine Learning)
    name: 강화학습 (Reinforcement Learning)
    output: true
    permalink: /:collection/:name
    tags:
    - lecture
    - machine_learning
    - snu
  Stanford_cs231n:
    category: 기계학습 (Machine Learning)
    name: Convolutional Neural Networks for Visual Recognition
    output: true
    permalink: /:collection/:name
    tags:
    - lecture
    - machine_learning
    - stanford
  calculus:
    category: 수학 (Mathematics)
    name: 미적분학 (Calculus)
    output: true
    permalink: /:collection/:name
    tags:
    - math
  etc:
    category: 기타 (Etc)
    name: 기타 (Etc)
    output: true
    permalink: /:collection/:name
    tags: []
  git:
    category: Git
    name: Git
    output: true
    permalink: /:collection/:name
    tags:
    - git
  javascript:
    category: 프로그래밍 언어 (Programming Language)
    name: Javascript
    output: true
    permalink: /:collection/:name
    tags:
    - programming_language
    - javascript
    - js
  jekyll:
    category: 웹 (Web)
    name: 지킬 (Jekyll)
    output: true
    permalink: /:collection/:name
    tags:
    - web
    - blog
  nas_ml:
    category: 기계학습 (Machine Learning)
    name: NAS
    output: true
    permalink: /:collection/:name
    tags:
    - library
    - numpy
    - python
  numpy:
    category: 라이브러리 (Libraries)
    name: Numpy
    output: true
    permalink: /:collection/:name
    tags:
    - library
    - numpy
    - python
  paper_review:
    category: 기타 (Etc)
    name: 논문 리뷰
    output: true
    permalink: /:collection/:name
    tags:
    - graduate_school
    - snu
  python:
    category: 프로그래밍 언어 (Programming Language)
    name: 'Re : 제로부터 배우는 파이썬'
    output: true
    permalink: /:collection/:name
    tags:
    - programming_language
    - python
  virtualbox:
    category: 응용 프로그램 (Applications)
    name: Oracle VM VirtualBox
    output: true
    permalink: /:collection/:name
    tags:
    - application
    - virtualbox
    - virtual_application
  vscode:
    category: 응용 프로그램 (Applications)
    name: VSCode
    output: true
    permalink: /:collection/:name
    tags:
    - vscode
  web_server:
    category: 웹 (Web)
    name: 웹 서버 (Web Server)
    output: true
    permalink: /:collection/:name
    tags:
    - web
    - server
  docker:
    output: true
    permalink: /:collection/:name
    name: docker
    category: 라이브러리 (Libraries)
    tags:
    - docker
    - server
defaults:
- scope:
    path: ''
    type: sysdoc
  values:
    layout: default
- scope:
    path: ''
    type: SKKU_swe3050
  values:
    layout: document
- scope:
    path: ''
    type: SNU_m3309.000200
  values:
    layout: document
- scope:
    path: ''
    type: Stanford_cs231n
  values:
    layout: document
- scope:
    path: ''
    type: calculus
  values:
    layout: document
- scope:
    path: ''
    type: etc
  values:
    layout: document
- scope:
    path: ''
    type: git
  values:
    layout: document
- scope:
    path: ''
    type: javascript
  values:
    layout: document
- scope:
    path: ''
    type: jekyll
  values:
    layout: document
- scope:
    path: ''
    type: nas_ml
  values:
    layout: document
- scope:
    path: ''
    type: numpy
  values:
    layout: document
- scope:
    path: ''
    type: paper_review
  values:
    layout: document
- scope:
    path: ''
    type: python
  values:
    layout: document
- scope:
    path: ''
    type: virtualbox
  values:
    layout: document
- scope:
    path: ''
    type: vscode
  values:
    layout: document
- scope:
    path: ''
    type: web_server
  values:
    layout: document
- scope:
    path: ''
    type: docker
  values:
    layout: document
